// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJILs_rHzTZtdIB4vDKfc-Pk75X7l-6h0',
    appId: '1:255861114206:web:1c5a84005c8dc507767bcf',
    messagingSenderId: '255861114206',
    projectId: 'quizart-984d9',
    authDomain: 'quizart-984d9.firebaseapp.com',
    storageBucket: 'quizart-984d9.appspot.com',
    measurementId: 'G-JZTFLMQMY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOnsZAfioWsbJTihOFmpH44xH85-4XY4k',
    appId: '1:255861114206:android:a5cda9ca4147e389767bcf',
    messagingSenderId: '255861114206',
    projectId: 'quizart-984d9',
    storageBucket: 'quizart-984d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsu1EsGD67WJyuV6spYKSkKSEJDaJwE0g',
    appId: '1:255861114206:ios:9b98609184aa706d767bcf',
    messagingSenderId: '255861114206',
    projectId: 'quizart-984d9',
    storageBucket: 'quizart-984d9.appspot.com',
    iosBundleId: 'com.google.firebase.presents.quizart',
  );
}
