// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChu6lKAjmUdCFGGNdZC-htefuNkpJZuFo',
    appId: '1:886114989692:web:0aafc37872ba1e9e1c7bf9',
    messagingSenderId: '886114989692',
    projectId: 'quizart-7102b',
    authDomain: 'quizart-7102b.firebaseapp.com',
    storageBucket: 'quizart-7102b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3E0UFntUBWg3cw0HvmcLQ_wDT7xXj0LU',
    appId: '1:886114989692:android:eaf7f3efba8f40951c7bf9',
    messagingSenderId: '886114989692',
    projectId: 'quizart-7102b',
    storageBucket: 'quizart-7102b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXyHuEBfSSaMnj-CgmO3Of9xQkTXbs0I',
    appId: '1:886114989692:ios:1432287f9a46a8231c7bf9',
    messagingSenderId: '886114989692',
    projectId: 'quizart-7102b',
    storageBucket: 'quizart-7102b.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXyHuEBfSSaMnj-CgmO3Of9xQkTXbs0I',
    appId: '1:886114989692:ios:416fc03eb2dc90dd1c7bf9',
    messagingSenderId: '886114989692',
    projectId: 'quizart-7102b',
    storageBucket: 'quizart-7102b.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo.RunnerTests',
  );
}
